name: iris
functions:
- url: ./src/iris.yaml
  name: xgb
- url: https://raw.githubusercontent.com/mlrun/functions/master/serving/xgboost/xgb_serving.ipynb
  name: serving
workflows:
  main: workflow.py
